config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:show, :new, :create, :index]
  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :participants, inverse_of: :event
  accepts_nested_attributes_for :participants, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :amount, numericality: { greater_than: 0 }, presence: true
  validates :participants, length: { minimum: 3, message: "must at least be 3" }
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event

  validates :name, presence: true
  validates :email, presence: true

  validate :format_of_email

  def format_of_email
    unless email.match?(/.+@.+[.].+/)
      errors.add(:email, 'is not in the right format')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!

  def index
    @events = current_user.events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      AssignSecretSanta.new(@event).perform
      redirect_to root_path, notice: "Event created, emails to the participants are on their way"
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :amount, participants_attributes: [:id, :name, :email])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div class='alert alert-danger p-2'>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @event do |f| %>
<div class="row">
  <div class="col">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control select2" %>
  </div>
  <div class="col">
    <%= f.label :amount %>
    <%= f.number_field :amount, class:"form-control select2" %>
  </div>
</div>
  <h3 class="mt-3">Participants</h3>
  <div id='participants'>
    <%= f.fields_for :participants do |participant| %>
      <%= render 'participant_fields', :f => participant %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add participant', f, :participants %>
    </div>
  </div>
  <%= f.submit 'Create', class:"btn btn-outline-dark mt-3 mb-3" %>
<% end %>

app/views/events/_participant_fields.html.erb
<div class='nested-fields'>
  <div class="row">
    <div class="col">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control select2" %>
  </div>
  <div class="col">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control select2" %>
  </div>
  </div>
  <%= link_to_remove_association "Remove participant", f %>
</div>

app/views/events/index.html.erb
<div class="container mt-1 mb-2">
  <h1>Organized events</h1>

  <% @events.each do |event| %>
    Title: <%= event.title %><br/>
    Amount: <%= event.amount %><br/>
    Participants:
    <% event.participants.each do |participant| %>
      <%= participant.name %> (<%= participant.email %>)
    <% end %><br/>
    <br/>
  <% end %>

  <%= link_to "Back to menu", root_path, class:"btn btn-warning mb-1"%>
</div>

app/views/events/new.html.erb
<h1 class="mt-1">Create an event</h1>

<%= render partial: "events/form", locals: {event: @event} %>

<%= link_to "Back to menu", root_path, class:"btn btn-warning mb-1"%>

app/views/home/index.html.erb
<div class="container-fluid p-5">

  <p>Organize a secret Santa event</p>

  <div class="container mb-3">
  <% if current_user %>
    <%= link_to "Create an event", new_event_path, class:"btn btn-success mt-3 mr-3"%>
    <%= link_to "Show events", events_path, class:"btn btn-warning mt-3 mr-3"%>
    <%= link_to "Disconnect", destroy_user_session_path, method: :delete, class:"btn btn-danger mt-3"%>
  <% else %>
    <%= link_to "Create account", new_user_registration_path, class:"btn btn-success mt-3 mr-3"%>
    <%= link_to "Connect", new_user_session_path, class:"btn btn-success mt-3"%>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/shared/bootstrap" %>

    <title>Santa Claus Is Coming To Town</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="jumbotron vertical-center">
      <div class="container text-center pt-2">
        <%= render "layouts/shared/flash_messages" %>
        <%= yield %>
      </div>
    </div>

    <%= render "layouts/shared/javascript" %>

  </body>
</html>

app/views/layouts/shared/_bootstrap.html.erb
  <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

app/views/layouts/shared/_flash_messages.html.erb
<% if notice %>
	<div class='alert alert-success p-2'>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger p-2'>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/shared/_javascript.html.erb
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>